name: Benchmark this PR
on:
  pull_request:
    branches:
      - master
      - '!compathelper/**'
    paths-ignore:
      - 'README.md'
      - 'test/**'
      - 'docs/**'
      - 'examples/**'
      - 'PyPlot/**'
permissions:
  pull-requests: write    # needed to post comments

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Add sample files
        run: |
          cd benchmark
          ln -s ../test/Artifacts.toml Artifacts.toml
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: '1'